# Matthew Carter Dylan Wilcox
DROP TABLE PICKUP_ORDER;
DROP TABLE DELIVERY_ORDER;
DROP TABLE DINE_IN;
DROP TABLE CUSTOMER;
DROP TABLE DISCOUNT_ORDER;
DROP TABLE PIZZA_TOPPING;
DROP TABLE DISCOUNT_PIZZA;
DROP TABLE PIZZA;
DROP TABLE SEAT;
DROP TABLE ORDERS;
DROP TABLE TOPPINGS;
DROP TABLE BASE_PRICE;
DROP TABLE DISCOUNTS;
