# Matthew Carter Dylan Wilcox
SELECT * FROM CUSTOMER;
SELECT * FROM ORDERS;
SELECT * FROM PICKUP_ORDER;
SELECT * FROM DELIVERY_ORDER;
SELECT * FROM DINE_IN;
SELECT * FROM TOPPINGS;
SELECT * FROM BASE_PRICE;
SELECT * FROM DISCOUNT_ORDER;
SELECT * FROM SEAT;
SELECT * FROM DISCOUNT_PIZZA;
SELECT * FROM PIZZA_TOPPING;
SELECT * FROM PIZZA;
SELECT * FROM DISCOUNTS;